//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rsx.Dumb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rsx.Dumb.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REM echo cd %SYSTEMROOT%\SysWow64\ &gt; &quot;%temp%\batch1.bat&quot;
        ///SET ba1=%temp%\batch1.bat
        ///SET ba2=%temp%\batch2.bat
        ///SET vb=%temp%\vb.vbs
        ///echo call %SYSTEMROOT%\SYSNATIVE\dism /online /enable-feature /featurename:&quot;MSMQ-Container&quot; &gt; %ba1%
        ///echo call %SYSTEMROOT%\SYSNATIVE\dism /online /enable-feature /featurename:&quot;MSMQ-Server&quot; &gt; %ba2%
        ///REM echo %SendKeys% &quot;n&quot; &gt;&gt;  &quot;%temp%\batch1.bat&quot;
        ///REM echo %SendKeys% &quot;n&quot; &gt;&gt;  &quot;%temp%\batch2.bat&quot;
        ///REM echo exit &gt; &quot;%temp%\batch1.bat&quot;
        ///echo Set UAC = CreateObject^(&quot;Shell.Applicat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string msmqx64 {
            get {
                return ResourceManager.GetString("msmqx64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REM echo cd %SYSTEMROOT%\SysWow64\ &gt; &quot;%temp%\batch1.bat&quot;
        ///SET ba1=%temp%\batch1.bat
        ///SET ba2=%temp%\batch2.bat
        ///SET vb=%temp%\vb.vbs
        ///echo call %SYSTEMROOT%\system32\dism /online /enable-feature /featurename:&quot;MSMQ-Container&quot; &gt; %ba1%
        ///echo call %SYSTEMROOT%\system32\dism /online /enable-feature /featurename:&quot;MSMQ-Server&quot; &gt; %ba2%
        ///REM echo %SendKeys% &quot;n&quot; &gt;&gt;  &quot;%temp%\batch1.bat&quot;
        ///REM echo %SendKeys% &quot;n&quot; &gt;&gt;  &quot;%temp%\batch2.bat&quot;
        ///REM echo exit &gt; &quot;%temp%\batch1.bat&quot;
        ///echo Set UAC = CreateObject^(&quot;Shell.Applicatio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string msmqx86 {
            get {
                return ResourceManager.GetString("msmqx86", resourceCulture);
            }
        }
    }
}
